### ISSUE TITLE
Broken normals on two models

### ISSUE THREAD

**Issue by Davide244** [TeamSpen210/HammerAddons#100]
vactube_90deg_06.mdl and vactube_90deg_01.mdl have broken normals on the top rail and glass (or whatever you call those black steel thingies) I didn't see it but I think all vactube curves have some weird normals.
![image](https://user-images.githubusercontent.com/69866130/91613145-4373c380-e97f-11ea-8105-2907c3aef912.png)
![image](https://user-images.githubusercontent.com/69866130/91613581-1a076780-e980-11ea-9a5f-9984f1822e93.png)

**Comment by Luke18033** [comment]
How is this related to HammerAddons? Those are vanilla models.

**Comment by Davide244** [comment]
I cam to this conclusion because the models were fine before the installation of HammerAddons

> How is this related to HammerAddons? Those are vanilla models.

**Comment by Luke18033** [comment]
They were not, HammerAddons doesn't touch those models.

**Comment by Luke18033** [comment]
And `vactube_90deg_01` doesn't even seem to have the problem...

**Comment by TeamSpen210** [comment]
This isn't really an issue to be solved by this.
