### ISSUE TITLE
npc_personality_core and prop_glados_core have no hitbox or model in hammer

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#102]
as the title says- when placing either one, they have nothing whatsoever and cannot be selected (or even seen for that matter).

they can also not be selected by any means other than the entity report after they have been de-selected.

**Comment by Luke18033** [comment]
That's odd, the model helpers should prevent this from happening. I'll take a look.

**Comment by Luke18033** [comment]
Seems to work fine for me?
![image](https://user-images.githubusercontent.com/19228201/91668367-17605b80-eac1-11ea-916f-7a62ccb36156.png)

**Comment by Fennecai** [comment]
thats super weird. maybe I should try updating again.... might have to do with my mod config

**Comment by Fennecai** [comment]
update: on my end it seems to work fine with the corrupt core set as the hammer model, it's only invisible with the Wheatley core.

**Comment by Fennecai** [comment]
oh no.... yeah it was completely on my end, feel free to close this. srry for wasting your time

**Comment by Luke18033** [comment]
That error appears if you have multiple game configurations, it's part of the hack to make it not always select P2. Just ignore it.
