### ISSUE TITLE
command line parameters need documentation or listing somewhere

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#107]
``--propcombine`` is not the only option this has; but nobody would know that unless you told them. So I'm suggesting you tell them by documenting it in the wiki or anywhere else. even a simple list would be better than nothing at all; though a brief description of what each one does would be good too.

reason:
I had trouble initially finding out about --nopack, and i cant figure out how to tint combined groups of models for debugging though i remember reading somewhere that i could. 

other people might have this issue as well.

**Comment by TeamSpen210** [comment]
You can run `--help` for a full list, but I should probably put it online as well.

**Comment by Fennecai** [comment]
case in point, haha.... didnt even know about --help. I was trying /? and -h as is conventional for lots of other stuff
