### ISSUE TITLE
prop_airboat_vehicle missing inputs

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/HammerAddons#109]
In the portal.fgd, the prop_airboat_vehicle doesn't have inputs like entervehicle and exitvehicle.

**Comment by Konclan** [comment]
Also note that using the exitvehicle input while a player isn't in an airboat causes portal to crash

**Comment by Luke18033** [comment]
I'd assume this was for PEE?

**Comment by Luke18033** [comment]
`EnterVehicle` doesn't exist outside of Mapbase according to the code.
