### ISSUE TITLE
Multiple classnames for comp_entity_finder doesn't work correctly

### ISSUE THREAD

**Issue by vanjac** [TeamSpen210/HammerAddons#111]
I was having trouble getting the cube dropper instances to work with a regular prop_weighted_cube. I would get this error message from the postcompiler:

`Cannot find valid prop_weighted_cube prop_monster_box entity within 192.0 units for entity finder at <-384 -736 288>! (fov=180.0, in direction 1 0 0)`

When I edited the instance and removed `prop_monster_box` from the list of classnames for the comp_entity_finder, the problems went away and the dropper started working correctly.

It seems like maybe #93 isn't totally fixed?

**Comment by TeamSpen210** [comment]
Do you have the latest version of the compiler copied in?

**Comment by vanjac** [comment]
I installed 2.1.6 from the releases page. should I be looking at dev branch?

**Comment by vanjac** [comment]
Is the source code for the postcompiler available anywhere? I can't find it in the repository.

**Comment by TeamSpen210** [comment]
It's in the [srctools](https://www.github.com/TeamSpen210/srctools) repository. I did some digging, for some reason I never included the updated code in the last release.

**Comment by vanjac** [comment]
thanks, I installed the new compiler and it fixed the cube dropper for both types of cubes.
