### ISSUE TITLE
L4D2 FGD Errors (That i found atleast)

### ISSUE THREAD

**Issue by lazyRares** [TeamSpen210/HammerAddons#112]
- The func_nav_blocker "teamtoblock" variable is defined twice, simply delete the first to fix it
- sky_camera is made an obsolete entity because on line 8720 clip_3d_skybox_near_to_world_far_offset has integer  "0.0" make it just 0 no quotes either. 
- The FGD is named l4d2.fgd, it should be left4dead2.fgd. 
- Info_Survivor_Rescue, and possibly Info_Survivor_Start all rotate weirdly, i had to rotate it 45 degrees and it would snap to 90 after.

**Comment by Luke18033** [comment]
I already reported the doubled rotation in #89, it's caused by the entity having multiple models set.

**Comment by lazyRares** [comment]
> I already reported the doubled rotation in #89, it's caused by the entity having multiple models set.

Thank you for informing me about this
