### ISSUE TITLE
P2: prop_<static/dynamic/override> entites, missing Hologram (Distort + fade) RenderFX option

### ISSUE THREAD

**Issue by gsgouvea91** [TeamSpen210/HammerAddons#121]
Noticed that the prop_<static/dynamic/override> entities are all missing the **Hologram (Distort + fade)** option in their RenderFX drop down menu.  I've switched to vanilla fgd to see if it might just had changed name, but the effect disappeared when I rolled back to the addons one.

**Comment by TeamSpen210** [comment]
I did some digging, and I had a good reason for removing those - they appear only supported in games before L4D.
