### ISSUE TITLE
Suggestion: Manual random().seed and rotation speed for vactube objects spinning

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#125]
When using the portal 2 vac tubes, there are some times where I like the way the objects spin better than other times. It seems to be random per-compile (looking at the code confirms as such despite my limited python knowledge)

Sometimes they tumble around really well around corners, but sometimes they look more like they are gliding- both cases are desirable for different situations or aesthetic preferences. sometimes I like the cubes violently slamming around in the tube corners, other times it looks better for them to sort of glide. 

I think it'd be good if the compiler output the randomized seed that was previously used; so if i like the rotations the objects make, i can find the seed in the log and then type it into the ``comp_vactube_start`` or ``comp_vactube_object``'s "random seed" keyvalue.

I would split the following into a separate issue but they seem tightly related, so here's my other suggestion:

Additionally, i noticed that the objects tumble faster when they are moving slower, and tumble slower when they move faster. this might be an illusion, as faster-moving objects will usually appear to be rotating slower from my experience, but that said, it would be a nice feature to be able to manually define how quickly or slowly the objects tumble around independent from the speed they move at.

A specific use-case i thought of, is making a map on the moon or in space: the vactube entities could be used/abused to create meteors floating by, if only the tumbling could be made slower.

another use case is more conventional in that slower-moving vac tubes sometimes look strange when the objects are still tumbling around really quickly. an example of that can be seen at the end of my workshop map: [On The Shoulders Of Giants](https://steamcommunity.com/sharedfiles/filedetails/?id=2200907877), where a cube moves somewhat slowly through a tube but tumbles quickly. it looks weird.

**Comment by TeamSpen210** [comment]
The rotation is currently entirely unaffected by the speed or movement of the path, and is indeed random every time. A seed would be good though. I also should make it take into account the direction/velocity of movement so it mainly rotates when going around corners.
