### ISSUE TITLE
Soundscript attribute error crash

### ISSUE THREAD

**Issue by treacherousfiend** [TeamSpen210/HammerAddons#128]
When attempting to compile a map, the postcompiler fails when attempting to load soundscripts with the error:

`[I] postcompiler.main(): Loading soundscripts...`
`[E] (unknown file).(unknown function)(): Uncaught Exception:`
`Traceback (most recent call last):`
  `File "srctools\scripts\postcompiler.py", line 219, in <module>`
  `File "srctools\scripts\postcompiler.py", line 96, in main`
  `File "srctools\packlist.py", line 541, in load_soundscript_manifest`
  `File "srctools\packlist.py", line 446, in load_soundscript`
  `File "srctools\packlist.py", line 468, in _parse_soundscript`
  `File "srctools\sndscript.py", line 219, in parse`
  `File "srctools\sndscript.py", line 122, in split_float`
`AttributeError: 'list' object has no attribute 'upper'`

Not entirely sure why this happens, i'm only using soundscripts which are in the game by default.
Additional info:
Game - TF2
Map located on different drive from game
Soundscript manifest generation disabled (error happens with it on as well)
The lines mentioned in the error seem to be ones that either load or parse the files.
from reading the code it seems like the postcompiler is supposed to make a soundscript if one is not found, but it is not doing so.

**Comment by TeamSpen210** [comment]
The problem is actually that my soundscript parser isn't able to parse one of TF2's soundscripts, I must have missed some syntax edge case. It also really needs some better error reporting, so it'll tell you the relevant file.

**Comment by treacherousfiend** [comment]
i see, i'll do some testing to see which ones in my map are causing the crash

**Comment by JimmyCabbage** [comment]
has this been resolved yet?

**Comment by treacherousfiend** [comment]
I have not tested it yet, but i'll try to compile the newest version it in a couple hours to see if it works

**Comment by TeamSpen210** [comment]
The referenced commit should fix the issue, I just haven't compiled a release.

**Comment by JimmyCabbage** [comment]
alright, cool!
