### ISSUE TITLE
Stop prop_testchamber_door from looping the close animation in Hammer

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#13]
I've already done this in my fork. Adding a read-only `defaultanim` keyvalue to the entity set to `idleclose` will force Hammer to play that animation, without the need for a custom version of the model (as you suggested on Discord when I asked about this a couple years ago).

**Comment by TeamSpen210** [comment]
Good idea, although the animation stuff in Hammer is pretty messed up, so it'd still be buggy.
