### ISSUE TITLE
Manual select props to combine

### ISSUE THREAD

**Issue by treacherousfiend** [TeamSpen210/HammerAddons#135]
Currently, static prop combining is done via an entity using bboxes. while this works in most scenarios, there are sometimes areas where a large prop's bbox overlaps smaller props. I suggest either a new entity or an extension to the current one to add a system to manually select props to combine.
Similarly, entities like env_cubemap and info_overlay can manually select faces to affect, and entities like light_spot can manually select entities in a similar fashion.

from a very base look at the FGDs, it appears that for the most part these entities do this by querying `target(target_destination)`, if that helps.

**Comment by TeamSpen210** [comment]
Indeed, the problem is that I can't add a name option to static props since vbsp parses and removes all its keyvalues. Note that only the prop's origin matters, and you can use the prop model to filter.

**Comment by treacherousfiend** [comment]
ooh I didn't realize that only the origin mattered, I assumed it was the whole bbox. i'll keep that in mind. Is it possible to use the prop's id since they don't have names? or does that differ from the VMF to the BSP?

**Comment by TeamSpen210** [comment]
There's no IDs or anything unfortunately in the BSP, the lump just contains [these values](https://developer.valvesoftware.com/wiki/Source_BSP_File_Format#Static_props) - just the keys that have an effect.

**Comment by treacherousfiend** [comment]
I see, do you want me to close this issue since it seems impossible?

**Comment by Luke18033** [comment]
You could maybe add something like a `comp_prop_static_marker` entity which you would place at the same position as a static prop to link it to a name or ID.
