### ISSUE TITLE
Add npc_hover_turret Entity on Portal 2

### ISSUE THREAD

**Issue by KaziPlays** [TeamSpen210/HammerAddons#138]

**Comment by Luke18033** [comment]
I just added this in my latest PR.

**Comment by KaziPlays** [comment]
sorry, but what is a PR? Pre-Release? if it is I'll close this.

**Comment by Luke18033** [comment]
The third tab at the top of this page.

**Comment by KaziPlays** [comment]
oh, so it isn't done

**Comment by Luke18033** [comment]
It will be in the next version.

**Comment by Luke18033** [comment]
This is now implemented

**Comment by KaziPlays** [comment]
I've installed hammer addons and It's not there, I'll leave this open until somebody explains.

**Comment by Luke18033** [comment]
It's definitely in there, make sure you have the latest version. Any errors in the Hammer console?

**Comment by KaziPlays** [comment]
Nothing, I search npc_hover_turret and it's simply not there.

**Comment by Luke18033** [comment]
The entity is definitely implemented so I don't know what your problem is

**Comment by Luke18033** [comment]
Can this issue be closed, I just checked and this is definitely in the latest release
