### ISSUE TITLE
Instance entities are not included in all FGDs

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#14]
It was recently discovered that instances can be enabled in any Source game, but the unified FGDs haven't yet been updated to reflect this. (Unless you're intentionally leaving them out?) If you do change this, it might also be a good idea to add some sort of note in the entity description in normally-unsupported games, telling the user they need to add a `GameData` key to the gameinfo for instances to work.

**Comment by Luke18033** [comment]
These are still missing from P1's FGDs.

**Comment by TeamSpen210** [comment]
P1 doesn't have them, I'm fairly sure.

**Comment by Luke18033** [comment]
They work if you add a `GameData` key to gameinfo.txt pointing to the FGD.

**Comment by Luke18033** [comment]
Still an issue, instances are functional in **all** pre-L4D games by adding `GameData`.
