### ISSUE TITLE
Suggestion: Core Rail Helpers

### ISSUE THREAD

**Issue by arRk-byte** [TeamSpen210/HammerAddons#153]
Like Vactube helpers but for rails.

This would help people make Behind the Scenes (with core and management rail) Portal 2 maps.

**Comment by Luke18033** [comment]
Not sure how helpful this would be, normal core rails are just `path_track`s anyway...with vactubes it was meant to replicate Valve's method where the objects flying through the tube are actually an animated model.

**Comment by TeamSpen210** [comment]
This doesn't seem that necessary, it's specialised and really you just want some instances.
