### ISSUE TITLE
Maps cannot be compiled with postcompiler on Infra

### ISSUE THREAD

**Issue by Davide244** [TeamSpen210/HammerAddons#156]
OS: Windows 11 - 64 Bit
Game: Infra
Postcompiler: 64 Bit
HammerAddons Version: Latest

I cannot compile maps on Infra. 90% of the time when I try to compile it crashes the postcompiler. When it does compile the map crashes the game on startup.

Here is the output from the compiler: https://www.toptal.com/developers/hastebin/edokezoyep.swift

And to confirm: I have installed HammerAddons correctly.

**Comment by TeamSpen210** [comment]
That's unusual.

**Comment by TeamSpen210** [comment]
I think I've fixed it, can you confirm by adding this to the `transforms` folder of the postcompiler? 
[prim_fix.zip](https://github.com/TeamSpen210/HammerAddons/files/8030062/prim_fix.zip)

**Comment by Davide244** [comment]
> I think I've fixed it, can you confirm by adding this to the `transforms` folder of the postcompiler? [prim_fix.zip](https://github.com/TeamSpen210/HammerAddons/files/8030062/prim_fix.zip)

Can confirm that this fixes the issue. Sorry for the late reply!
