### ISSUE TITLE
Vactubes dont work due to a vscript error.

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#158]
this error happens in the console when I try to use the vactube system to create a cube dropper. (previous versions of the postcompiler didn't have this issue even with the exact same setup of the vactube dropper thing)

```
AN ERROR HAS OCCURED [the index 'obj' does not exist]

CALLSTACK
*FUNCTION [main()] INJECT_4e7f05f367fa87a2.nut line [1]

LOCALS
[this] TABLE
Error running script named inject/INJECT_4e7f05f367fa87a2.nut

AN ERROR HAS OCCURED [the index 'anim' does not exist]

CALLSTACK
*FUNCTION [main()] INJECT_5e19b1ab2c0de99d.nut line [2]

LOCALS
[this] TABLE
Error running script named inject/INJECT_5e19b1ab2c0de99d.nut
```

after opening up the bsp in VIDE to check the scripts themselves out, they both seem to only be one line each. not sure if that's intentional; but the scripts _are_ there at least, so the problem is beyond the scope of what I am able to self-debug.

**Comment by TeamSpen210** [comment]
Looks like you're missing the [vactube VScript](https://github.com/TeamSpen210/HammerAddons/blob/master/hammer/scripts/vscripts/srctools/vac_anim.nut) , which is in the `hammer/` folder.

**Comment by Fennecai** [comment]
well, no, its in my folder. guess it just doesn't get packed correctly automatically or something.
