### ISSUE TITLE
Postcompiler doesn't understand "update" folder precedence

### ISSUE THREAD

**Issue by BurntPudding** [TeamSpen210/HammerAddons#164]
Whenever a map is compiled using the postcompiler, the `upgrade_potatogun` command is called. This does not happen when I disable the postcompiler.

**Comment by TeamSpen210** [comment]
The problem is actually that you have auto-packing enabled, causing it to pack the transition script. But it's packing one from the wrong folder.

**Comment by BurntPudding** [comment]
How do I make it not do that?
