### ISSUE TITLE
Postcompiler doesn't do static prop combine if gameinfo path != portal2/

### ISSUE THREAD

**Issue by TheEnderek0** [TeamSpen210/HammerAddons#165]
When you set up a different path in `gameinfo` the Postcompiler behaves very weirdly in StaticPropCombine.
It doesn't detect which props to combine, and if it does there's 90% chance it will random ones that aren't even in the radius of comp_propcombine_set.
However, if you trick it to think it's compiling for `portal2` it will work fine. I just created a `portal2/` folder just with the main gameinfo.txt and it worked.

NOTE: Only the staticpropcombine doesn't work then, the rest works fine.

**Comment by TeamSpen210** [comment]
That doesn't make much sense, since I don't look for `portal2` anywhere in the code, and it works fine in Desolation for example which doesn't have a `portal2` folder at all.

**Comment by TheEnderek0** [comment]
Fixed, this was a problem on my side

**Comment by TeamSpen210** [comment]
Anything I could tweak to make it obvious what the problem was?

**Comment by TheEnderek0** [comment]
It was mainly the problem with P2CE mounting system, but for some reason it logged that the groups were empty, while on portal2/ folder it detected them but not combined. Everything seems to work fine now though, now that I mounted the assets in srctools.vdf.
