### ISSUE TITLE
comp_fakeplayer

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#167]
comp_fakeplayer would be a qol hammer-only entity (entirely removed from the map during compile) that has it's targetname set to ``!player`` as readonly in the fgd, and has all the valid inputs that the player entity can accept; as listed here:
https://developer.valvesoftware.com/wiki/Player

The purpose of this would be to make i/o more convenient to use with the !player entity. instead of having to look up the above page each time you wanna change the fog or force drop objects etc, and hope you spelled and capitalized the inputs right, you could just pick the input from the dropdown like any other entity.

it works because when you set it up like that with the targetname set to ``!player``, hammer can target it like its a normal entity despite the ``!``. then when in-game, even though the fake player entity is gone, those i/o chains are still referencing ``!player`` by name, so their outputs still correctly affect the real player entity.

I know this would be really quite easy to do because I have created it myself using hammer++'s editor text as a basis in a custom fgd. (i used that because its the only entity i knew that would be removed in the compile process in a way that wouldn't cause problems, but if there's another way; i would rather use that.)

what might be slightly more involved is outputs; which I think could be done by having the postcompiler create a clientcommand that would ``addoutput`` stuff on the actual player at map spawn, based on whatever was configured on the ``comp_fakeplayer`` entity in hammer.

**Comment by Fennecai** [comment]
> That's a clever trick!

thanks. :)



> In Portal 2, the name should be a choices dropdown which also has `!player_blue` and `!player_orange` since those can be used to refer to the Coop bots.

that's a good idea. I'll add that to my version until this is added to the hammer addons officially. :)

**Comment by Adrthegamedev** [comment]
One thing I would like to add: there are some attributes of `player` that can only be changed using `addoutput` due to being keyvalues, like the `movetype` keyvalue; is there any way of implementing support for these?

**Comment by TeamSpen210** [comment]
That'll require the postcompiler to rewrite them into AddOutput, which is a little bit more complicated.

**Comment by Fennecai** [comment]
> That'll require the postcompiler to rewrite them into AddOutput, which is a little bit more complicated.

couldn't my suggestion in the last paragraph work as an easier method?

> what might be slightly more involved is outputs; which I think could be done by having the postcompiler create a clientcommand that would addoutput stuff on the actual player at map spawn, based on whatever was configured on the comp_fakeplayer entity in hammer.
