### ISSUE TITLE
Add Portal 2 - Educational Version support?

### ISSUE THREAD

**Issue by wertercatt** [TeamSpen210/HammerAddons#171]
_Portal 2 - Educational Version_ includes new entities, and new keyvalues for a few entities. These are included in its modified FGD files. It would be nice if these could be added to the unified FGD, perhaps using a `P2EV` tag to supplement the existing `P2` tag.

For convenience, I have created a git patch using the 'histogram' diff algorithm to compare P2EV's FGD files with those shipped with the current Steam build of P2. The folders used contained all four FGD files (`base.fgd`, `halflife2.fgd`,  `portal.fgd`, and `portal2.fgd`) as shipped with the appropriate builds. `halflife2.fgd` doesn't appear in the patch however, as it's the only FGD file to not receive any changes.

The patch can be found here: https://gist.github.com/wertercatt/2c5fe7ee8664f7d5ae4f0360b4164333

**Comment by Luke18033** [comment]
Might as well, it's just a few extra entities and this does support Sixense which is a similarly obscure version. The FGD probably won't be included with releases though, so you'd have to build that yourself from the repo which is pretty easy to do if you have python installed.

**Comment by Adrthegamedev** [comment]
I've been slowly chipping away at this on [my fork](https://github.com/Adrthegamedev/HammerAddons/), along with some experimentation with The Stanley Parable's branch, if you're interested.

**Comment by Adrthegamedev** [comment]
Aight, just be warned that TSP is very unfinished; I've only implemented a few bits and bobs from it so far.
