### ISSUE TITLE
comp_flicker_generic and comp_flicker_light

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#173]
A generic version of comp_flicker with outputs that can be configured and sent to any entity. useful for lights, audio loops for said lights, sprites, etc.

I've already coded this actually as a plugin on my end, but IDK how to do the whole git pull request thing, so here is the code for you to add and tweak if you'd like to implement it: https://mega.nz/folder/trJADI5Z#z4zOAVCQdOSEwVVMnCqNsg

**Comment by TeamSpen210** [comment]
Looks like I need better docs for the entity, this isn't actually necessary at all, it's already fully generic. The "model" field isn't required, it's there for convenience to add `OnTurnedOn` and `OnTurnedOff` outputs for you. You just need to add additional outputs to control whatever destination you care about.

**Comment by Fennecai** [comment]
ah- yeah, better docs would be nice. I created that whole genericized version just because of it lol. good to know
