### ISSUE TITLE
Unicode Reverse Line Feed Character in Visgroups

### ISSUE THREAD

**Issue by wertercatt** [TeamSpen210/HammerAddons#174]
I recently did a full compile of the unified FGDs ([artifacts here](https://wertercatt.com/HammerAddons/build/)) on Linux and discovered that some visgroups have a Unicode Reverse Line Feed (U+008D) at the end of their names. This is presumably unintentional, and results in some visgroups being duplicated. I'll use p2.fgd as an example.

"Gameplay/Excursion Funnels" is duplicated, both containing prop_tractor_beam, but with one of the groups ending with the control character.  
"Gameplay/Buttons" is duplicated as well, with func_button, func_rot_button, func_weight_button, and momentary_rot_button in one visgroup without the control character, while prop_button, prop_floor_ball_button, prop_floor_button, prop_floor_cube_button, prop_under_button, and prop_under_floor_button in a second visgroup with the character.

**Comment by TeamSpen210** [comment]
This actually is an intentional trick, it allows me to have the same name in multiple placed in the hierarchy - the Portal buttons are under `Test Elements/Buttons`, not `Gameplay`. When I originally did it it Hammer didn't display the character, but perhaps something changed, and I need a different one?

**Comment by wertercatt** [comment]
To be honest, I only saw the trick character because I was looking at the fgd on iOS and went 'what is that box and why are there duplicated groups?'

**Comment by TeamSpen210** [comment]
Ah, if it's working in Hammer fine still, this isn't a problem (perhaps should be documented).
