### ISSUE TITLE
[TF2] Propcombine fails to combine

### ISSUE THREAD

**Issue by kamuixmod** [TeamSpen210/HammerAddons#176]
Due to lack of documentation, it could be probable that the Issue might be due to wrongful setup of comp_propcombine_set.

Following Error is output when trying to combine a multiple of props with the same model:

[INFO] mdl_compiler.__enter__(): Found 0 existing models/maps/first_room30halfmethod_smallersize_backup/propcombine/*
[WARNING] propcombine.group_props_ent(): Unused comp_propcombine_set at -2731 -3168.97 888.021
[INFO] propcombine.combine(): Combined 531 props into 531 groups (0 this compile):
 |  - 0 grouped models
 |  - 0 ineligible
 |  - 531 failed to combine
 |___
[first_room30halfmethod_smallersize_backup.log](https://github.com/TeamSpen210/HammerAddons/files/9421204/first_room30halfmethod_smallersize_backup.log)
![Untitled](https://user-images.githubusercontent.com/13024796/186571118-ead7d553-6751-4c1c-9668-7e9518a950ce.png)

![Untitled](https://user-images.githubusercontent.com/13024796/186571040-1261581c-0819-4be1-92f8-5b76cbf29ea3.png)

**Comment by TeamSpen210** [comment]
That looks wrong, yeah. What you need to do is change the mins/maxes to surround the props you want to combine together. It'd be easier though to use `comp_propcombine_volume`, so you can just use a brush, or enable the auto combine range option so it's automatic. The model filter isn't required also, that's there in case you want the set to apply to only some models.

**Comment by kamuixmod** [comment]
Yeah would've loved to but it does not seem to be an option for some reason
![Untitled](https://user-images.githubusercontent.com/13024796/186582770-a26af579-e2bd-472f-8000-a78bcbbca120.png)

**Comment by TeamSpen210** [comment]
It's a brush entity.

**Comment by kamuixmod** [comment]
Alright, tried it with the method you mentioned above
![Untitled](https://user-images.githubusercontent.com/13024796/186583973-5cb86d96-8b57-44af-a871-9b41832e1979.png)

i am getting this error message however
![Untitled](https://user-images.githubusercontent.com/13024796/186584175-087e945a-e8b8-4dc5-8c66-9795d94faf4d.png)

**Comment by TeamSpen210** [comment]
The issue there is actually from `studiomdl`, check the log file to see the full error.

**Comment by kamuixmod** [comment]
Yeah i think the main issue could've been that i didn't use the toolspropcombine texture, though what's the best method of checking visually if it properly combined those props?

**Comment by TeamSpen210** [comment]
Turn on `r_colorstaticprops`, and each prop will be tinted a different colour. You could also browse `models/maps/yourmapname/propcombine/` and inspect the results.

**Comment by TeamSpen210** [comment]
This seems to be resolved.
