### ISSUE TITLE
Calling Cancel on a comp_choreo_sceneset doesn't stop upcoming scenes from playing

### ISSUE THREAD

**Issue by TheNitram21** [TeamSpen210/HammerAddons#177]
Any help with this would be appreciated, as I plan on finishing my map the next days.

**Comment by TeamSpen210** [comment]
The generated scenes are named `nameofscene`, `nameofscene_1`, `nameofscene_2` etc, so you'll need to call `Cancel` on either `nameofscene*` or the specific one you need to cancel. I should have it reroute `Cancel` to all of them though.
