### ISSUE TITLE
The particle browser crashes hammer ++

### ISSUE THREAD

**Issue by CoaLMaN122PL** [TeamSpen210/HammerAddons#178]
Using the particle browser with hammer addons 2.5.1 crashes hammer ++ with an access violation, but only for portal 2
![obraz](https://user-images.githubusercontent.com/51474134/193069933-c99b1736-af07-4908-be09-1dbc74c8e004.png)

**Comment by TeamSpen210** [comment]
I don't include any particles, the only thing that could affect this is the addition/absence of FGD entries perhaps. Regardless this would be a bug in Hammer++, not here - it should cope with different keys.
