### ISSUE TITLE
(api support request I guess) Compiling as a static prop in the postcompiler

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#181]
I made an addon for the postcompiler to add a comp_prop_labmonitor that just acts as a more convenient way to place the lab monitor models in a map. (pose and skin key values with descriptive names such as "downward tilt" and "aperture logo")

For now, I've coded it to use prop_dynamic, which works. However, it is slightly inefficient, I think. I'd like to use prop_static instead, but of course, the engine doesn't recognize that entity and removes it because static props arent entities; they are the same as a world brush without any tied entity, as far as I know.

I wonder if there is an example I'm unaware of or something I could reference that shows me the right way to place a static prop through the postcompiler. This is the .py addon in its entirety, configured in a way that doesn't work:

```
"""Implements comp_prop_labmonitor"""
from srctools import conv_bool, conv_float
from srctools.logger import get_logger

from hammeraddons.bsp_transform import trans, Context


LOGGER = get_logger(__name__)


@trans('comp_prop_labmonitor', priority=10)
def comp_prop_labmonitor(ctx: Context):
    """Implements comp_prop_labmonitor, the easier way to place monitor screen models."""
    
    for monitor in ctx.vmf.by_class['comp_prop_labmonitor']:
        LOGGER.info('creating monitor prop with skin' + monitor['skin'] + 'and model' + monitor['model'])
        ctx.vmf.create_ent(
            'prop_static',
            origin=monitor['origin'],
            skin=monitor['skin'],
            model=monitor['model'],
            angles=monitor['angles'],
            renderamt=monitor['renderamt'],
            rendercolor=monitor['rendercolor']
        )

```

**Comment by TeamSpen210** [comment]
Indeed static props are not entities, they have a specific lump in the BSP. What you need to do is import [`srctools.bsp.StaticProp`](https://srctools.readthedocs.io/en/v2.3.5/modules/bsp.html#srctools.bsp.StaticProp) and [`StaticPropFlags`](https://srctools.readthedocs.io/en/v2.3.5/modules/bsp.html#srctools.bsp.StaticPropFlags), then append that to `ctx.bsp.props`. For example here's [prop ropes](https://github.com/TeamSpen210/HammerAddons/blob/c34de0861c2f7f9e80b2cbb1bc71d45aaef6dce5/transforms/geocable.py#L1114), and [propcombine](https://github.com/TeamSpen210/HammerAddons/blob/c34de0861c2f7f9e80b2cbb1bc71d45aaef6dce5/src/hammeraddons/propcombine.py#L255). A challenging bit to deal with is that static props store which visleafs they overlap, so you'll have to calculate that. This is [how I do it for prop ropes](https://github.com/TeamSpen210/HammerAddons/blob/c34de0861c2f7f9e80b2cbb1bc71d45aaef6dce5/transforms/geocable.py#L1036), unfortunately using a fair bit of math knowledge.

**Comment by Fennecai** [comment]
oh wow, thats way more involved than i thought it would be. guess I'll just have to place my monitors by hand for what its worth lol... thanks for the reply though. (i suck at math)
