### ISSUE TITLE
Entity Lump parse failure

### ISSUE THREAD

**Issue by OrsellGaming** [TeamSpen210/HammerAddons#184]
Hi,

I'm getting an error every time I try to run the post compiler when I compile my map. Every time I get this error, the number in front of "Failed to execute..." changes every time I compile. I'm unsure if this is an error code, but the python error returned is the same every time "ValueError: not enough values to unpack (expected 2, got 1)".

Here is a picture of the console:
![image](https://user-images.githubusercontent.com/34631691/203692671-9393d5b3-8ceb-498f-904d-a69c8f09960c.png)

I've tried reinstalling, and it seems to fix itself, but then one or two more compiles later, the error returns. I am using Hammer ++ for Portal 2, I'm aware Portal 2 doesn't have official support for Hammer ++, but I've grown tired of the constant crashes with normal Hammer :(.

The way I reinstalled it was by using HAInstaller, and I've also manually installed it in case that also works, but I get the same result. I seem to have, unfortunately, also broken the sprites for all the hammer entities in Hammer while doing this. Hammer does detect the hammer entity sprites though in the texture library but it's not applying them. While that's not as big of an issue, and I can deal with it, it's just kinda annoying. 

Here is an example of that sprite issue with an env_instructor_hint:
![image](https://user-images.githubusercontent.com/34631691/203692504-100a511a-9af2-4bff-88c4-2a270c09f37d.png)

Any help would be greatly appreciated!
Thanks!

**Comment by TeamSpen210** [comment]
This error is coming from the postcompiler failing to parse the entity data lump in the BSP. To figure out why, I do need to have a look at the BSP it's trying to read. You could send it privately via Discord (`TeamSpen210#7765`) or Steam (`TeamSpen210`), or something else?

**Comment by OrsellGaming** [comment]
Hi @TeamSpen210, thanks for helping me out. I can send it via Discord if that's fine with you. It's a fixed version of Into The Multiverse Part 1 for the P2MM mod and for general coop sessions. My username is `Orsell#5280` so you that it's me, I will delete this comment later for my own privacy reasons too btw.

**Comment by TeamSpen210** [comment]
Aha, the problem is caused by the `\n` in this `game_text`:
```vdf
"targetname" "p2mm_start_text"
"spawnflags" "1"
"message" "Map Will Begin Soon...
Please Wait For Your Partner..."
```
For speed I'm using a simpler parser which doesn't handle things like this. I'm not sure if it even works ingame?

**Comment by TeamSpen210** [comment]
Related: #78.

**Comment by OrsellGaming** [comment]
That's weird, "\n"'s work with `game_text`, in fact, they are helpful instead of having several `game_text` entities. I can understand why the post compiler would freak out over it because in the vmf it actually is just a return carriage and not a "\n". Do you think it's possible to add compatibility for "\n"'s in the future or will I need another `game_text`? Similar to how quotes are converted to tildes for VScript?

**Comment by OrsellGaming** [comment]
Just checked the mentioned issue, I'll see how the compiler reacts when I use `/n` instead of `\n` maybe it would work?

**Comment by OrsellGaming** [comment]
Ok using `/n`'s also cause it to fail, and after removing them it still fails. Something else is causing an issue with the compiler. Same error too.

**Comment by OrsellGaming** [comment]
There shouldn't be or isn't, any other `\n`'s in the map besides two `game_text` entities at the very start. I could have missed something. Let me check again, but if not, then we still have an issue.

**Comment by OrsellGaming** [comment]
Ok so it does seem that all the `\n`'s in my `game_text` entities were causing the problem.

**Comment by Luke18033** [comment]
How do you use `\n` in a game_text without it getting changed to a forward slash, does that only happen in some engine branches?

**Comment by OrsellGaming** [comment]
Is the postcompiler reading it from the bsp or the vmf? If it's reading the bsp shouldn't it grab information it couldn't handle with the bsp from the maps vmf? Isn't this issue similar to quotes corrupting the vmf also, it just need to switch out the \n with something it can read properly?

**Comment by TeamSpen210** [comment]
It's reading from the BSP, it can't grab things from the VMF because it could be in an instance. Yeah it's the same sort of issue as quotes, except I deliberately used simpler code since I expected this couldn't be added to the file. I've fixed it now by switching to my full parser code so it'll handle all special cases.
