### ISSUE TITLE
Failed to execute script due to unhandled exception.

### ISSUE THREAD

**Issue by SierraRay53** [TeamSpen210/HammerAddons#185]
I was installing Hammer++ for Portal 2 from the guide. It required HammerAddons to work and setting up PostCompiler just errors out.

**Tried Fixes**
- "-game $gamedir" to the parameters
- adding game folder path in srctools.vdf

**Results of these fixes**
**_Not Working_**

Images:
![image](https://user-images.githubusercontent.com/81502335/204675450-21044eec-460d-4ee9-b65d-e3ce94d2781e.png)
![image](https://user-images.githubusercontent.com/81502335/204675635-1ff9275c-55aa-4dfb-957a-755cffe635bd.png)

**Comment by TeamSpen210** [comment]
Follow the instructions in the 3rd-last line there.

**Comment by TeamSpen210** [comment]
Is the `srctools.vdf` config you're editing in the location on the 3rd line?

**Comment by SierraRay53** [comment]
I'm quite confused there...
Is this the third line in srctools? I tried adding "/portal2" or "/csgo". It just reverts back to none.
![image](https://user-images.githubusercontent.com/81502335/204752824-9c67f37a-290c-41a1-9d9b-f9f140f4efe5.png)

**Comment by TeamSpen210** [comment]
Ah, did you not remove the comment markers at the start?

**Comment by SierraRay53** [comment]
Oh! I see why. Now it worked! Thanks.
