### ISSUE TITLE
[BMS] Prop combine fails

### ISSUE THREAD

**Issue by ImJustJacob** [TeamSpen210/HammerAddons#187]
As far as I know the current setup is fine, I am using comp_propcombinevolumes, with the appropriate tool texture if that matters.
Postcompiler identifies and decompiles all the props, their QCs and meshes seem to be ok.
StudioMDL doesn't seem to throw any errors, besides some 2D physics hull warnings.

However, the resultant models show up as errors in game, and the models, when decompiled, just appear to be a meshes triangles compressed into a single vert.

See relevant part of log.
https://pastebin.com/wbuhhnCX

We would greatly appreciate help in getting this working, as performance is limited in some prop heavy parts of our maps.

**Comment by TeamSpen210** [comment]
Okay, what's happening is that I'm ending up parsing Black Mesa BSPs wrongly, assuming that they have support for CSGO's static prop scaling. So they're being built with a scale of 0, hence the compressed models.

**Comment by ImJustJacob** [comment]
> Okay, what's happening is that I'm ending up parsing Black Mesa BSPs wrongly, assuming that they have support for CSGO's static prop scaling. So they're being built with a scale of 0, hence the compressed models.

Good to know, BMS runs on a modded TF2 branch according to a dev, if that info helps any.
