### ISSUE TITLE
Add propcombine group option for specifying model destination.

### ISSUE THREAD

**Issue by WereTech** [TeamSpen210/HammerAddons#188]
The combiner is great for temporary use, grouping a bunch of my props together in singular passes then replace my current models with those, however it will reset the whole model folder when I remove the combiner brush entities (probably doing this regardless on each compile) so I'm forced to copy the models into a separate folder each time. It would be great to have a parameter that can tell the compiler to not remove the other models so I can keep them all in one place without the inconvenience.

**Comment by TeamSpen210** [comment]
The way the combiner is intended to be used is not for you to replace stuff manually - instead, you run it on the map every time, it'll swap the models in the mal. Then it'll  store and reuse the models in your next compile. I may want to implement a separate command that lets you put the groups somewhere else, so you can precompile things like instances though.
