### ISSUE TITLE
Vactube droppers use `model` KV and ignore `cubetype`.

### ISSUE THREAD

**Issue by DrPeeper228** [TeamSpen210/HammerAddons#192]
Name says everything(cubes are not dissolving and there is no replacement cubes)

**Comment by DrPeeper228** [comment]
[ha_vactube_dropper.zip](https://github.com/TeamSpen210/HammerAddons/files/10419986/ha_vactube_dropper.zip)

**Comment by TeamSpen210** [comment]
If you look at the log file, you'll find these lines:
```
[WARNING] __init__.vactube_transform(): Cube model "models/props/metal_box.mdl", skin 0 is not a type of cube travelling in this vactube!
 | 
 | Add a comp_vactube_object entity with this cube model with the group "cube".
 |___
```
The postcompiler doesn't look at the cube type value itself for cubes here, it just looks at the model field which you still have set as the regular cube type. Set that to a reflection cube as well and it'll then work properly.

**Comment by Luke18033** [comment]
Should probably have it only use the model keyvalue if cubetype > 5, otherwise choose from the base cube models
