### ISSUE TITLE
comp_auto

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#199]
Like `comp_relay` but for `logic_auto`. If the control type/value is true then it'll convert into a `logic_auto`, otherwise it'll get deleted during compile.

**Comment by TeamSpen210** [comment]
Hmm, this can be accomplished already by just chaining those two entities. `logic_auto`s get merged, then the relay will strip the output.

**Comment by Luke18033** [comment]
I forgot about the logic_auto combining, I guess that makes this not as useful then, except maybe looking cleaner in Hammer
