### ISSUE TITLE
How to make propcombine work?

### ISSUE THREAD

**Issue by ExR1337** [TeamSpen210/HammerAddons#204]
How do I use this function? I tried using it like the valve one but it seems not to work for some reason. Can I maybe get a .qc example?
Please? I'm trying to get some railings to combine...
__________________________________________________

[I] logger.log(): Combining props...
[I] logger.log(): Parsing QC files. Paths:
 | D:\SteamLibrary\steamapps\common\content
 |___

[W] logger.log(): Cannot parse "D:\SteamLibrary\steamapps\common\content\csgo\models\railings_combine.qc"... (None, None)
[I] logger.log(): Done! 5 prop QCs found.
[I] logger.log(): Propcombine sets present (1), combining...
[I] logger.log(): Found 0 existing models/maps/de_test/propcombine/*
[I] logger.log(): Culled 0 models in models/maps/de_test/propcombine/*
[I] logger.log(): Combined 190 props into 190 groups (0 this compile):
 |  - 0 grouped models
 |  - 0 ineligible
 |  - 190 failed to combine
 |___

**Comment by TeamSpen210** [comment]
It doesn't work like Valve's system. You don't need to provide a QC template, what it's looking for are the original/decompiled QCs of the props, so it has the geometry necessary. It's easier though just to turn on the decompile option, which will run the models through Crowbar automatically.

**Comment by ExR1337** [comment]
How do I provide propcombine groups properly? It did decompile all of custom props this time, but it still didn't output anything.

_____________

[I] logger.log(): Done! 5 prop QCs found.
[I] logger.log(): No propcombine groups provided.
[I] logger.log(): Done!

**Comment by TeamSpen210** [comment]
You want to create either `comp_propcombine_volume` (use `tools/toolsprocombine`) or `comp_propcombine_set` entities, and surround the origins of a particular group of props you want to be merged. Alternatively or in addition, set the auto-propcombine range in `srctools.vdf`, which will automatically combine props that close together instead of you specifying groups manually. If you do both the manual groups take precedence of course.

**Comment by ExR1337** [comment]
It didn't work so I tried with barrels. But it still gave me this error. Is there a fix for this? Btw I used the automatic installer for hammer addons.
____________________________________________
[I] logger.log(): Done! 1 prop QCs found.
[I] logger.log(): Propcombine sets present (1), combining...
[I] logger.log(): Found 0 existing models/maps/de_test/propcombine/*
[I] logger.log(): Compiling maps/de_test/propcombine/mdl_8209.mdl...
[I] logger.log(): Parsing ref "C:/Users/ExR/Desktop/content/cstrike/models/barrel_b.smd#0"
[I] logger.log(): Parsing coll "C:/Users/ExR/Desktop/content/cstrike/models/barrel_b_physics.smd"
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "hammeraddons\acache.py", line 55, in fetch
KeyError: (frozenset({PropPos(x=-9.6666667, y=0.0, z=-13.3333333, pit=0.0, yaw=0.0, rol=0.0, model='models/props/barrel_b/barrel_b.mdl', checksum=b'\xf5\xe2\xe6t', skin=0, scale=1.0, solidity=<CollType.VPHYS: 6>), PropPos(x=18.8333333, y=0.0, z=-15.3333333, pit=0.0, yaw=0.0, rol=0.0, model='models/props/barrel_b/barrel_b.mdl', checksum=b'\xf5\xe2\xe6t', skin=0, scale=1.0, solidity=<CollType.VPHYS: 6>), PropPos(x=-9.1666667, y=0.0, z=28.6666667, pit=0.0, yaw=0.0, rol=0.0, model='models/props/barrel_b/barrel_b.mdl', checksum=b'\xf5\xe2\xe6t', skin=0, scale=1.0, solidity=<CollType.VPHYS: 6>)}), True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 315, in <module>
  File "trio\_core\_run.py", line 2010, in run
  File "hammeraddons\postcompiler.py", line 201, in main
  File "hammeraddons\propcombine.py", line 1129, in combine
  File "trio\_core\_run.py", line 850, in __aexit__
  File "hammeraddons\propcombine.py", line 1124, in do_combine
  File "hammeraddons\propcombine.py", line 248, in combine_group
  File "hammeraddons\mdl_compiler.py", line 192, in get_model
  File "hammeraddons\acache.py", line 59, in fetch
  File "hammeraddons\mdl_compiler.py", line 239, in _compile
  File "trio\_subprocess.py", line 708, in run_process
  File "trio\_subprocess.py", line 403, in open_process
  File "trio\_threads.py", line 215, in to_thread_run_sync
  File "trio\_core\_traps.py", line 166, in wait_task_rescheduled
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 161, in do_release_then_return_result
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 175, in worker_fn
  File "subprocess.py", line 1022, in __init__
  File "subprocess.py", line 1491, in _execute_child
PermissionError: [WinError 5] Access is denied
[9640] Failed to execute script 'postcompiler' due to unhandled exception!

**Comment by TeamSpen210** [comment]
You likely need to change the `studiomdl_path` option, it might be incorrect for CSGO.

**Comment by ExR1337** [comment]
Yes it looked correct but it wasn't and I changed it and it still didn't work so I decided to put the vmf file in the csgo's directory and that fixed it. Thank you for you time kind sir ☺️
