### ISSUE TITLE
OnTransitionFinished output for comp_numeric_transition

### ISSUE THREAD

**Issue by Qwerbey** [TeamSpen210/HammerAddons#210]
I would like a fake output for comp_numeric_transition that fires after the entity has sent all the keyvalue/input changes.  This is already possible by using OnTrigger and setting the delay to the same value as the duration, but it'd be really convenient to have it tied to the keyvalue.

**Comment by TeamSpen210** [comment]
Why didn't I add that originally? Definitely should be there.
