### ISSUE TITLE
How to build the postcompiler from source?

### ISSUE THREAD

**Issue by WereTech** [TeamSpen210/HammerAddons#213]
I'm not quite sure what I'm doing wrong, but I eventually got to the point where I've reached an impossible to debug error. I have all requirements installed but it hitches at this for both the main and dev branch. It also completes at the size of ~12 MB which is a lot more than the usual size of the executables you've provided in the packages. I'm trying to do this so I can make any changes that I need but I can't do that with these errors showing up.
```
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 40, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "win32com\__init__.py", line 5, in <module>
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.
[14428] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by TeamSpen210** [comment]
What Python version are you using, and is it a fresh virtual environment? I'm fairly sure nothing actually requires `win32com`, so I'm not sure why this error is occurring.

**Comment by WereTech** [comment]
My current version is 3.11.1. I do see that the latest is 3.11.3 so I may try again with that one to see if it's the same.

**Comment by TeamSpen210** [comment]
That should be fine.

**Comment by WereTech** [comment]
So now I'm not really sure what's going on. I'm just using pyinstaller on the postcompiler.py and it outputs the exe and base_library.zip. Can you give a full list of details of what exactly you do to compile it? Even just commands or possibly a program you use to do it for you.

**Comment by TeamSpen210** [comment]
Ahh. You want to run PyInstaller on the [`postcompiler.spec`](https://github.com/TeamSpen210/HammerAddons/blob/dev/postcompiler.spec) file in the repo root. I also have [CI](https://github.com/TeamSpen210/HammerAddons/blob/master/.github/workflows/build-postcompiler.yml) setup, so you could potentially fork the repo and get it that way. Though, the `plugins` config option lets you load any scripts in, so most things should be doable that way.

**Comment by WereTech** [comment]
If I try to use pyinstaller on the .spec in the root it just says that the postcompiler.py cannot be found

**Comment by WereTech** [comment]
Yeah it still returns the same error when running on that .spec in root.

**Comment by TeamSpen210** [comment]
Ahh, you need the working directory to be in `src/`. Probably should move it in there.

**Comment by WereTech** [comment]
Ok now it says that hammeraddons cannot be found, but not sure where to get that from?

**Comment by TeamSpen210** [comment]
That should resolve to `<repo>/src/hammeraddons/_version.py`, allowing it to compile the version into the executable. Not sure why [that global](https://pyinstaller.org/en/stable/spec-files.html#globals-available-to-the-spec-file) wouldn't be working, perhaps add a `print(SPECPATH)` call...

**Comment by WereTech** [comment]
It returns `E:\Users\Owner\Documents\GitHub\HammerAddons\src\hammeraddons`

**Comment by WereTech** [comment]
Going to give a successful log to see if you can pick out anything wrong here, because running the spec from anywhere other than the root doesn't work, and directly running on the .py also gives the same result. https://pastebin.com/PLy4FSZb

**Comment by TeamSpen210** [comment]
You might need to do `pyinstaller ../postcompiler.spec` from the `src/` folder?

**Comment by WereTech** [comment]
Works but exactly the same error when running the postcompiler.exe

**Comment by WereTech** [comment]
Ok, apparently I needed this, which isn't really shown anywhere else so I didn't know I needed it. (I haven't ever built programs for Python, however other languages I have so I certainly know to look for whatever they may need)
`python -m pip install -U setuptools pip wheel`
So I was missing setuptools and wheel

**Comment by StefanH-AT** [comment]
For things like this, it's useful to look at the github workflow and copy the steps in there.
https://github.com/TeamSpen210/HammerAddons/blob/0413539f4b5f902683e46c30e0fbdee8292a5903/.github/workflows/build-postcompiler.yml#L31
