### ISSUE TITLE
 Reading BSP ... struct.error: unpack_from requires a buffer of at least xxxxxxx bytes

### ISSUE THREAD

**Issue by devallround** [TeamSpen210/HammerAddons#218]
I get this Error when trying to run the postcompiler with L4D2 on win11
tried version 2.5.1 and 2.5.2 with different map files  ( manual install )
perhaps any idea how i can get this to run ?

`[I] postcompiler.main(): HammerAddons postcompiler, srctools=v2.3.3, addons=v2.5.1
[I] postcompiler.main(): Map path is e:\steamlibrary\steamapps\common\left 4 dead 2\sdk_content\mapsrc\cu01\cu_sky_006.bsp
[I] config.parse(): Config path: "e:\steamlibrary\steamapps\common\left 4 dead 2\srctools.vdf"
[I] config.parse(): Game folder: E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2
[I] postcompiler.main(): Loading plugins...
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\branchlistener_uniquestate.py" as "hammeraddons.plugins.builtin.branchlistener_uniquestate"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_entity_finder.py" as "hammeraddons.plugins.builtin.comp_entity_finder"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_entity_mover.py" as "hammeraddons.plugins.builtin.comp_entity_mover"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_flicker.py" as "hammeraddons.plugins.builtin.comp_flicker"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_kv_setter.py" as "hammeraddons.plugins.builtin.comp_kv_setter"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_numeric_transition.py" as "hammeraddons.plugins.builtin.comp_numeric_transition"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_relay.py" as "hammeraddons.plugins.builtin.comp_relay"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_scriptvar_setter.py" as "hammeraddons.plugins.builtin.comp_scriptvar_setter"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\comp_sequential_call.py" as "hammeraddons.plugins.builtin.comp_sequential_call"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\geocable.py" as "hammeraddons.plugins.builtin.geocable"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\p2_antline.py" as "hammeraddons.plugins.builtin.p2_antline"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\p2_brush_ents.py" as "hammeraddons.plugins.builtin.p2_brush_ents"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\portal2.py" as "hammeraddons.plugins.builtin.portal2"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\sceneset.py" as "hammeraddons.plugins.builtin.sceneset"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\vactubes\__init__.py" as "hammeraddons.plugins.builtin.vactubes"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\vactubes\animations.py" as "hammeraddons.plugins.builtin.vactubes.animations"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\vactubes\nodes.py" as "hammeraddons.plugins.builtin.vactubes.nodes"
[I] plugin.load_all(): Loading "E:\SteamLibrary\steamapps\common\Left 4 Dead 2\bin\postcompiler64\transforms\vactubes\objects.py" as "hammeraddons.plugins.builtin.vactubes.objects"
[I] postcompiler.main(): Gameinfo: E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2
[I] postcompiler.main(): Search paths:
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\update\pak01_dir.vpk
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\update\pak01_dir.vpk
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2_dlc3\pak01_dir.vpk
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2_dlc2\pak01_dir.vpk
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2_dlc1\pak01_dir.vpk
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2\pak01_dir.vpk
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\update
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\update
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2_dlc3
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2_dlc2
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2_dlc1
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\left4dead2
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\hl2
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\hammer
 | E:\SteamLibrary\steamapps\common\Left 4 Dead 2\platform
 |___

[I] postcompiler.main(): Loading soundscripts...
[I] postcompiler.main(): Done! (20265 sounds)
[I] postcompiler.main(): Loading particles...
[I] postcompiler.main(): Done! (1815 particles)
[I] postcompiler.main(): Reading BSP...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 287, in <module>
  File "trio\_core\_run.py", line 1946, in run
  File "hammeraddons\postcompiler.py", line 125, in main
  File "srctools\bsp.py", line 1138, in __init__
  File "srctools\bsp.py", line 1237, in read
struct.error: unpack_from requires a buffer of at least 3234756 bytes for unpacking 16 bytes at offset 3234740 (actual buffer size is 3234748)
Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 287, in <module>
  File "trio\_core\_run.py", line 1946, in run
  File "hammeraddons\postcompiler.py", line 125, in main
  File "srctools\bsp.py", line 1138, in __init__
  File "srctools\bsp.py", line 1237, in read
struct.error: unpack_from requires a buffer of at least 3234756 bytes for unpacking 16 bytes at offset 3234740 (actual buffer size is 3234748)
[4844] Failed to execute script 'postcompiler' due to unhandled exception!
Finished. Press a key to close.`

**Comment by TeamSpen210** [comment]
L4D2's BSP format must be different in some way here to what's expected.

**Comment by devallround** [comment]
checked bytes of Authorings Tools´ "tutorial07_complete.bsp" build with my version against a non-german version from a friend, files are identical

**Comment by TeamSpen210** [comment]
Found the problem, a weird L4D2-specific shuffling around of some values for no reason whatsoever.
