### ISSUE TITLE
map won't run

### ISSUE THREAD

**Issue by thad4002** [TeamSpen210/HammerAddons#229]
[INFO] postcompiler.main(): HammerAddons postcompiler, srctools=v2.3.9, addons=v2.5.2
[INFO] postcompiler.main(): Map path is c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\porttest1.bsp
[INFO] config.parse(): Config path: "c:\program files (x86)\steam\steamapps\common\portal 2\srctools.vdf"
[INFO] config.parse(): Paths config: c:\program files (x86)\steam\steamapps\common\portal 2\srctools_paths.vdf
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 315, in <module>
  File "trio\_core\_run.py", line 2010, in run
  File "hammeraddons\postcompiler.py", line 100, in main
  File "hammeraddons\config.py", line 171, in parse
ValueError: No game folder specified!
Add -game $gamedir to the command line, or set it in "c:\program files (x86)\steam\steamapps\common\portal 2\srctools.vdf".

**Comment by TeamSpen210** [comment]
It needs to know which game it's running in, did you specify either of those?

**Comment by thad4002** [comment]
where do i specify?

**Comment by TeamSpen210** [comment]
See the last line in the log you posted.

**Comment by GalaxxyGem** [comment]
Looks like we had the same issue
