### ISSUE TITLE
specifically prohibited paths still pack

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#233]
I have been trying to set up a development workflow for a mapbase mod. However, it seems that the postcompiler still dumps a bunch of hl2 vanilla files despite multiple attempts on my part to specifically prohibit them from being packed, unless i turn auto_pack to 0 but thats not helpful because using comp_pack isn't packing all required resources (such as the actual vtfs or or model meshes), and its cumbersome to use for every single custom asset.

in srctools_paths.vdf, i have:
```
"hl2" "G:/[sombodys] stuff/program files/Steam/SteamApps/common/half-life 2/"
```

and in srctools.vdf i have:

```
	"searchpaths"
		{
		"path" "|hl2|ep2/"
		"nopack" "|hl2|ep2/"
		"path" "|hl2|episodic/"
		"nopack" "|hl2|episodic/"
		"path" "|hl2|hl2/"
		"nopack" "|hl2|hl2/"
		}

```
I tried putting those same paths in the "pack_blocklist" section (properly formatted ofc) and it didn't work there either.

**Comment by TeamSpen210** [comment]
Can you attach a copy of the log file? In particular, look for `Allowed filesystems:`, which will list all the paths mounted and for each whether they should pack (`+`) or not (`-`). The blocklist part works a little differently, you specify part/all of the actual files themselves - `materials/tools/` for instance.

**Comment by Fennecai** [comment]
[postcompiler.log](https://github.com/TeamSpen210/HammerAddons/files/12270475/postcompiler.log)

here.

**Comment by TeamSpen210** [comment]
I noticed in your filesystems list you have mapbase mounted, plus a bunch of copies of extracted game stuff. Are the mistakenly packed files coming from those?

**Comment by Fennecai** [comment]
nope, i checked. none of those paths contain vanilla hl2 files
