### ISSUE TITLE
Setting pack_dump causes vactubes anims not to be packed

### ISSUE THREAD

**Issue by ElliotElison** [TeamSpen210/HammerAddons#257]
I don't know if this was intentional or not, but I found it very unintuitive that setting a pack_dump directory causes even the vactube anims not to be packed. If this was intentional, consider changing it.

**Comment by TeamSpen210** [comment]
If you enable that configuration, absolutely nothing is packed, everything gets written to that folder instead. It's mostly intended as a debugging feature.
