### ISSUE TITLE
Oversized env_dustpuff and env_muzzeflash icon sprites

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#27]
You can see the two sprites here. An info_player_start and an `O B S O L E T E` sprite are placed next to them, for comparison.
![hammer_2019-12-27_12-23-00](https://user-images.githubusercontent.com/19228201/71531603-3e1c2180-28a4-11ea-9cc5-1adf4bbcc6bf.png)
![image](https://user-images.githubusercontent.com/19228201/71531597-39f00400-28a4-11ea-8479-ae92ba31684a.png)

**Comment by TeamSpen210** [comment]
This is because these entities have a `scale` keyvalue, which Hammer is hardcoded to use to resize the sprites. Real annoying, and I can't do much about unless I make a model.

**Comment by Luke18033** [comment]
Maybe you could store it as something like `spritescale` or `comp_scale`, then use the postcompiler to rename the keyvalue so the engine recognizes it.
