### ISSUE TITLE
Single quote characters should not be escaped

### ISSUE THREAD

**Issue by vrad-exe** [TeamSpen210/HammerAddons#286]
The FGD exporter appears to attempt to escape single quotes (`'`) in strings with a backslash, which is incorrect and causes this weird bug where previous letters get duplicated.
![image](https://github.com/user-attachments/assets/96d180df-9e59-44c3-9126-c49ba6ed48d3)
![image](https://github.com/user-attachments/assets/97a0e5e5-3d4f-4171-a9e6-2e79f72b5f46)

**Comment by TeamSpen210** [comment]
Ah yeah sorry, this is TeamSpen210/srctools#35.
