### ISSUE TITLE
Remove env_terrainmorph from FGDs

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#30]
This entity is not implemented in any current engine branches as far as I know. If it actually is, the entity at least needs to be excluded from newer games' FGDs.

**Comment by TeamSpen210** [comment]
It's a weird thing that was shown off in an E3 demo or the like (it lets you distort the shape of displacements), but cut from HL2 itself.

**Comment by Luke18033** [comment]
I know what it does, I used it in the leak.
