### ISSUE TITLE
bee2_ entities included in Portal 2 FGD, should be separate

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#34]
The title says it all.

**Comment by TeamSpen210** [comment]
Note the BEE2 entities are not actually present in here, they're contained in that repo.

**Comment by Luke18033** [comment]
I checked and didn't have `bee2.fgd` added in Hammer, so I assumed you included them here. I guess that was an accident? Though the models/sprites aren't on the BEE2 repos either as far as I know...

**Comment by Luke18033** [comment]
![image](https://user-images.githubusercontent.com/19228201/71539102-25375e80-28ec-11ea-9173-6664b7faeead.png)
The BEE2 ents are definitely in here.

**Comment by TeamSpen210** [comment]
As it says in that comment, BEE2 writes those into the FGD file - I needed to do that to ensure they work when compiling the instances. Just delete everything after the comment, then set  `BEE2 EDIT FLAG = 0`.
