### ISSUE TITLE
portal_race_checkpoint uses incorrect model

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#36]
The correct model is `models\effects\cappoint_hologram.mdl` (the incentivizing nugget/TF2 capture point model). The skin should also be kept default (this actually carries over to the game, messing up the coloring). I know this entity is unused and doesn't do anything useful as far as we know, but part of the point of these addons is to be as accurate to the game as possible, so this should be fixed regardless. It has the correct model in the default FGDs, so I'm not even sure why you changed it in the first place.

**Comment by TeamSpen210** [comment]
I assumed that this was the ending point for challenge mode.
