### ISSUE TITLE
Add Black Mesa support

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#38]
As with Valve's, the default Black Mesa FGDs have lots of entities without icons, missing keyvalues, lack of helpers, etc. Support for Black Mesa should be added to these addons so they can be used with its Absolutely Ancient Software™. All the entities from `bms.fgd` would need to be merged in, and it would also be a good idea to compare `halflife2.fgd` and `base.fgd` with the original versions using Diffchecker to see if anything has changed there that needs to be ported over.

**Comment by TeamSpen210** [comment]
The script has an `import` command for this, but given all the changes made I have to manually go through the changes it performs and sanity check them all.
