### ISSUE TITLE
Prevent health/suit chargers from looping their use animation

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#42]
Similarly to #13, health/suit chargers in HL2 and Black Mesa default to the animation of them being used. I tried the Default Animation trick like I originally did for P2 doors, but it doesn't work in this Hammer version, and the models don't have any suitable animations anyway. To solve the problem, custom models for the chargers should be created that don't animate. The Black Mesa chargers additionally have dirty variants; these should be added with a fake `[H] Skin` keyvalue.

* [x] HL2 Health Charger
* [x] HL2 Suit Charger
* [x] Mesa Health Charger
* [x] Mesa Suit Charger

**Comment by Luke18033** [comment]
Now implemented

**Comment by TeamSpen210** [comment]
Not for Black Mesa.

**Comment by Luke18033** [comment]
Ah, I was wondering where those models were. Nowhere, I guess.
