### ISSUE TITLE
Ability to add delay to the dissolve trigger in comp_trigger_p2_goo

### ISSUE THREAD

**Issue by SpyceTewan** [TeamSpen210/HammerAddons#48]
With the trigger close to the surface, objects that fall in disappear early before they are fully submerged. Lowering the trigger allows players to swim on the surface

Suggestion: Add keyvalue to set a delay to the dissolve trigger

**Comment by TeamSpen210** [comment]
Actually I think I'll add an option to lower the dissolve trigger further down, and add some fade options so it can be used for bottomess pits as well.

**Comment by SpyceTewan** [comment]
Even better if you're able to implement that
