### ISSUE TITLE
portal 2 vactube system needs clearification

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#49]
The vac tube entities don't seem to work or make sense. with 0 documentation; there is just no way to tell how to properly use them. for example, this is my setup in a developer test map which doesnt seem to do anything at all: 
![image](https://user-images.githubusercontent.com/10889213/75393436-54962780-58ab-11ea-9af5-b89baf4a04e5.png)

I suggest either making the instructions clearer in the in-hammer "help" button screen or change these to use a more typical key/value system to set the targets and stuff like the path_track entities do for example.

**Comment by TeamSpen210** [comment]
There's actually a bug I missed where if you don't have at least 1 `comp_vactube_object` with "cube model" set, it won't work properly. Those don't need to be placed near the tubes, they're shared among all spawners in the map.

**Comment by Fennecai** [comment]
ah ok
