### ISSUE TITLE
portal 2 vactube system plays incorrect animations with multiple tracks

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#52]
When there are multiple vactube "tracks" in the map using this system which are completely seperate from eachother; (dont merge or split from/with eachother in any way) vactube items can be seen following the wrong paths in-game.

for example, if there is a completely straight track, and a seperate track that curves in different directions, you'll sometimes see vactube items on the straight track curve around the same as if they were on the curved track- and likewise, you may sometimes see items on the curved track behave the same as if they were on the straight track.

**Comment by TeamSpen210** [comment]
Did you restart the game after compiling? Models are kinda weird, even after restarting the map it might continue to use an old version of the model.

**Comment by Fennecai** [comment]
yes, i did.

**Comment by Fennecai** [comment]
![image](https://user-images.githubusercontent.com/10889213/76362717-1fe09200-62e7-11ea-823b-07497a080e65.png)
this diagram might help to explain better

**Comment by Fennecai** [comment]
I've done further tests on my end- this still doesn't work. I have tried having multiple vac tube item entities, placing the tracks in separate rooms where the visleaves are also separated, set the spawners to different timings.

It seems that rather than playing the correct animation for each tube path; it instead plays a random animation, including animations from other tubes in the map.

I havent personally seen/looked at the code, but if i had to guess, this might be because you coded it to compile all animations to one model, and it chooses random animations because users might want multiple items going through the tubes randomly. this makes sense, but results in the bugged behavior because, if im right about this, there is not a functioning check to make sure the animation being chosen belongs to the same track the spawner belongs to- so therfor, it plays random animations out of a list of _every animation in the map_.

**Comment by TeamSpen210** [comment]
I figured out the problem yesterday. I implemented a recycling feature which reuses the objects in the map, to try and help performance. But I missed adding a command to teleport it to the location of the spawner - so the objects would spawn from their original spawner.

**Comment by TeamSpen210** [comment]
Yep.
