### ISSUE TITLE
Change "move_rope" model to use the thick axis helper

### ISSUE THREAD

**Issue by HugoBDesigner** [TeamSpen210/HammerAddons#54]
The "move_rope" Hammer model is the thin axis helper, which is difficult to select, especially from afar. Meanwhile, "keyframe_rope" uses the thick axis helper, which is much easier to handle.
![image](https://user-images.githubusercontent.com/6296061/76713263-0f248780-66fe-11ea-8305-c4421199f1b3.png)

**Comment by TeamSpen210** [comment]
Just use the `keyframe_rope` entity for all of them, they're completely interchangeable :P.

**Comment by HugoBDesigner** [comment]
I know, I know. Just figured it'd be nice to have it consistent :P

**Comment by Fennecai** [comment]
hmm...this has me thinking though; @TeamSpen210 why don't you just remove one of them altogether since they are functionally identical now? I could see it causing problems with old maps that use both entities, but it's easy to adapt.

**Comment by TeamSpen210** [comment]
I want to have accurate FGDs, containing every entity that's useful.
