### ISSUE TITLE
comp_entity_mover's Direction's "Point At..." button saves the values to the wrong keyvalue

### ISSUE THREAD

**Issue by Flash4433** [TeamSpen210/HammerAddons#56]
![image](https://user-images.githubusercontent.com/38331230/77070523-4c309880-69e2-11ea-9554-a9e1bfcc2d74.png)

Upon using the "Point At..." button in the `direction` keyvalue, the value will get saved to `angles` instead of `direction`. This seems like a easy fix, but it might not be possible to do without modifying the source code?... Not sure.

**Comment by TeamSpen210** [comment]
I can't fix that, unfortunately.
