### ISSUE TITLE
env_sprite colors the axis helper but not the sprite

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#57]
env_spite entities with a custom color appear to color their axis helper in hammer, but not the actual sprite. this can make it slightly inconvenient to distinguish between sprites of different colors within hammer. an alternative solution to the problem I would suggest if coloring the actual sprite doesn't work is make a grayscale version of the axis helper, that way the red green and blue doesn't get blended with the color in a way that isn't helpful. another way to solve it might be to just remove the axis helper. I haven't experimented with FGD stuff much but from what I know, it seems possible.

this might conflict with issue #10 however...

**Comment by TeamSpen210** [comment]
I unfortunately can't change the special colour changing Hammer does, but making it greyscale is a good idea.

**Comment by Luke18033** [comment]
Wouldn't it be better to just remove the axis helper, so the color apples to the sprite itself? That's how it was previously and I never had a problem with it.

**Comment by Fennecai** [comment]
@Luke18033 i was thinking the same thing but if he did that, issue #10 would be un-done and idk if he wants to do that.

**Comment by Luke18033** [comment]
For me it's not showing a helper at all, making the entity impossible to select. I think it might be a good idea to just revert this to how it was before, the current setup seems way too buggy.

**Comment by Luke18033** [comment]
Actually, it doesn't look like the default version gets colored at all, which I thought it did. In that case TeamSpen's method would probably be best for this.

**Comment by Luke18033** [comment]
Now fixed
