### ISSUE TITLE
Postcompiler does not properly support old input syntax

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#69]
Prior to Left 4 Dead 2, input items were separated by commas instead of a special escape character (so `rturretEnable0.1-1` would simply be `rturret,Enable,,0.1,-1`). However, the postcompiler does not seem to properly support this, removing almost all outputs from entities instead. This makes the postcompiler unusable in older games, without essentially sacrificing the entire I/O system (not an option when VScript doesn't exist either).

**Comment by TeamSpen210** [comment]
Ah yeah. The slight issue is that in the BSP, outputs and keyvalues are just grouped all together - so it isn't immediately obvious which are which. I might make it use the FGD database to help with this.

**Comment by Luke18033** [comment]
Bump

**Comment by Luke18033** [comment]
This is not fixed

**Comment by TeamSpen210** [comment]
It should be now - note that the map needs to have at least one output present, for it to be able to detect which type to use. If not you have to specify it in the config file.

**Comment by Luke18033** [comment]
Okay, the auto-detection seems to be broken, it works correctly after manually setting the key in srctools.vdf

**Comment by Luke18033** [comment]
I'm not sure exactly what you mean by "the map needs to have at least one output present" - if there aren't any outputs in the map, this doesn't happen in the first place.

**Comment by TeamSpen210** [comment]
If there's an output present it should be able to detect the first one then know which to produce. But it looks like I messed up that logic, it doesn't work right. Fixed.
