### ISSUE TITLE
Add vactube cross junctions

### ISSUE THREAD

**Issue by L89David** [TeamSpen210/HammerAddons#79]
Maybe this is hard to imprement, but it would be nice to be able to do this type of junction:
![Sin título](https://user-images.githubusercontent.com/48654552/80618419-a68e3180-8a43-11ea-9f90-05b192a26ecd.png)

Btw, it's amazing how good the vactube creation works, amazing work.

**Comment by Luke18033** [comment]
Duplicate of #71.
