### ISSUE TITLE
prop_weighted_cube supports Wake and Sleep as inputs

### ISSUE THREAD

**Issue by DrMeepster** [TeamSpen210/HammerAddons#81]
`prop_weighted_cube` should have the `Wake` and `Sleep` inputs added to its FGD, as they do work on it.

**Comment by Luke18033** [comment]
This would be somewhat related to #74 (inheriting stuff from prop_physics).

**Comment by TeamSpen210** [comment]
It's a duplicate of that. It actually is a subclass, so it supports most of what that does.
