### ISSUE TITLE
ambient_generic has no spinup or spindown input

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#84]
ambient_generic's help page shows that the pitch-sliding features use the "spinup" and "spindown" inputs to function, however, there appear to be no such inputs. a work-around I'm using for now is using the comp_numeric_transition, but it'd be nice to not need it for this.

**Comment by Luke18033** [comment]
These don't exist in the engine as far as I can tell.

**Comment by TeamSpen210** [comment]
For Portal 2, a better solution would be operator stacks. There you can more directly fade pitch and any other value however you need.

**Comment by Fennecai** [comment]
while that is true; it's kind of unwieldy to create a sound script just for one-time use in a mod/map...i can totally do that since my mod is a big project anyway, but it'd be something worth thinking about. maybe enable those in the fgd, and if it doesn't exist in the engine normally, maybe have the post compiler implement it by compiling the numeric transition and such itself?

like if an ambient_generic has spinup or spindown being sent to it, the compiler would then detect that and compile the correct logical ents into the map to make the desired result happen, even if the user didn't place those ents themselves.

**Comment by TeamSpen210** [comment]
Looking into the code for this, seems like the inputs never existed, it's just automatically applied when starting the `ambient_generic`.
