### ISSUE TITLE
Automatically handle per-map particle manifests in the postcompiler

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/HammerAddons#92]
In most Source games, it's possible to pack particles into maps by using a per-map manifest, located at `maps/<mapname>_particles.txt`. The postcompiler's autopacker should support this, automatically generating the file and packing it in under the correct name if custom particle systems are used in the map or if the PCFs are specified in a `comp_pack`.

This feature was inexplicably missing from Portal 2 for nearly a decade. It's likely still missing from some other newer games, so the functionality would need to be disabled there.

**Comment by Luke18033** [comment]
Portal 2 now supports this

**Comment by TeamSpen210** [comment]
Yep, I first need to write a PCF file parser so I can match system names to their particle - and also what resources they use.

**Comment by Fennecai** [comment]
also worth noting; the description in the srctools.vdf is wrong. portal 2 does not use ``particles/<map name>_manifest.txt``, it uses ``maps/<map name>_particles.txt``.

**Comment by TeamSpen210** [comment]
Whoops.
