### ISSUE TITLE
Fix env_steam hammer helper

### ISSUE THREAD

**Issue by DarviL82** [TeamSpen210/HammerAddons#94]
Currently, the shape of the steam preview in Hammer is incorrectly rotated 90 degrees more.
Would be nice if we could have the same preview as `light_spots`... We could see the size of the steam much more easier, instead of seeing a static gray triangle.

**Comment by Luke18033** [comment]
I fixed the orientation, added a frustum helper, and made the model white so it matches the selected color:
![hammer_kAhTekqwnO](https://user-images.githubusercontent.com/19228201/120264202-1fb51500-c252-11eb-9d76-3400d4de03ba.png)
![hammer_QHnzP9n5cv](https://user-images.githubusercontent.com/19228201/120264207-20e64200-c252-11eb-83c6-9137012d66c5.png)
